version: "3"

services:
  test-php-server:
    build: .
    image: maddog986/php-nginx-mysql-server:latest
    container_name: test-php-server
    ports:
      - 8081:80
      - 3306:3306
    restart: unless-stopped
    environment:
      - WEBSITE_HOSTNAME=localhost:8081

  test-wordpress-server:
    build: .
    image: maddog986/php-nginx-mysql-server:latest
    container_name: test-wordpress-server
    ports:
      - 8082:80
    restart: unless-stopped
    environment:
      - WEBSITE_HOSTNAME=localhost:8082
      - WORDPRESS_INSTALL=true
