version: "2"

services:
  test-server:
    build: .
    image: maddog986/php-nginx-mysql-server:latest
    container_name: test-server
    ports:
      - 80:80
      - 3306:3306
      - 2222:2222
    restart: unless-stopped
    environment:
      - PHPMYADMIN_VERSION=4.9.4
