version: "2"

services:
  test-server:
    build: .
    image: maddog986/php-nginx-mysql-server:latest
    container_name: test-server
    ports:
      - 8080:80
    restart: unless-stopped
    environment:
      - WEBSITE_HOSTNAME=localhost:8081
      # - WORDPRESS_INSTALL=true
      # - WORDPRESS_TITLE=WordPress
      # - WORDPRESS_ADMIN_USERNAME=admin
      # - WORDPRESS_ADMIN_PASSWORD=admin
      # - WORDPRESS_ADMIN_EMAIL=drew@dpg.host
